
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PLAYBOLD!!
 */
public class customer_portal extends javax.swing.JFrame {
Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * Creates new form customer_portal
     */
    public customer_portal() {
        super("Customer Portal");
        initComponents();
        conn=jconnect.ConnecrDb();
        setResizable(false);
        date();
        time();
    }
     public void date(){
      String tdate=new SimpleDateFormat("dd/MM/YY",Locale.ENGLISH).format(new Date());
      date.setText("" +tdate);
  }
  public void time(){
      new Timer(0,new ActionListener(){
          @Override
          public void actionPerformed(ActionEvent ae){
              java.text.SimpleDateFormat ad=new java.text.SimpleDateFormat("HH:mm:ss");
              String ttime=ad.format(new Date());
              time.setText("" +ttime);
          }
      }).start();
              
          }
  public void custlogout1(){
       String sql="insert into custlog(Outdate,Outtime,Acc_No) values (?,?,?)";
        try{
                   pst=conn.prepareStatement(sql);
                   pst.setString(1,date.getText());
                   pst.setString(2,time.getText());
                   pst.setString(3,lbl1.getText());
                  pst.execute();
 }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
       finally{
            try{
                rs.close();
                pst.close();
     
            }
            catch(Exception e){
              
                
            }
        }
      
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        date = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        transfer = new javax.swing.JLabel();
        deposit = new javax.swing.JLabel();
        detailtrans = new javax.swing.JLabel();
        bot = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mini = new javax.swing.JLabel();
        withdraw = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        lbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/12.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/13.jpg"))); // NOI18N

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Apps-session-logout-icon(2).png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        date.setEditable(false);
        date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        time.setEditable(false);
        time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "WELCOME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        transfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/966_-_Transaction-128.png"))); // NOI18N
        transfer.setText("TRANSFER");
        transfer.setToolTipText("TRANSFER");
        transfer.setPreferredSize(new java.awt.Dimension(58, 14));
        transfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferMouseClicked(evt);
            }
        });

        deposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if_open_safety_box_44868.png"))); // NOI18N
        deposit.setToolTipText("DEPOSIT");
        deposit.setPreferredSize(new java.awt.Dimension(58, 14));
        deposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositMouseClicked(evt);
            }
        });

        detailtrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Passbook-128.png"))); // NOI18N
        detailtrans.setToolTipText("DETAIL TRANSACTIONS");
        detailtrans.setPreferredSize(new java.awt.Dimension(58, 14));
        detailtrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailtransMouseClicked(evt);
            }
        });

        bot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FAQs-128.png"))); // NOI18N
        bot.setToolTipText("FAQ's");
        bot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/21-128.png"))); // NOI18N
        jLabel7.setToolTipText("FEEDBACK");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dollar-01-128.png"))); // NOI18N
        mini.setToolTipText("MINI STATEMENT");
        mini.setPreferredSize(new java.awt.Dimension(88, 14));
        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMouseClicked(evt);
            }
        });

        withdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking_withdraw_money-128.png"))); // NOI18N
        withdraw.setToolTipText("WITHDRAW");
        withdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withdrawMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(withdraw, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(mini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detailtrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deposit, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(withdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bot, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(detailtrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        name1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("HELLO!!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(time)
                            .addComponent(date)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(time)
                        .addGap(11, 11, 11)
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(221, 221, 221))
        );

        setSize(new java.awt.Dimension(540, 731));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMouseClicked
        // TODO add your handling code here:
         setVisible(false);                                        
                cust_withdraw ob=new cust_withdraw();
             ob.setVisible(true);
             cust_withdraw.jacc.setText(lbl1.getText());
             cust_withdraw.jname.setText(name1.getText());
    }//GEN-LAST:event_withdrawMouseClicked

    private void depositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositMouseClicked
        // TODO add your handling code here:
         setVisible(false);                                        
                cust_deposit ob=new cust_deposit();
            ob.setVisible(true);
            cust_deposit.kacc.setText(lbl1.getText());
            cust_deposit.kname.setText(name1.getText());
    }//GEN-LAST:event_depositMouseClicked

    private void transferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferMouseClicked
        // TODO add your handling code here:
         setVisible(false);                                        
                cust_transfer ob=new cust_transfer();
            ob.setVisible(true);
            cust_transfer.lacc.setText(lbl1.getText());
            cust_transfer.lname.setText(name1.getText());
    }//GEN-LAST:event_transferMouseClicked

    private void botMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botMouseClicked
        // TODO add your handling code here:
         setVisible(false);                                        
                chatbot ob=new chatbot();
            ob.setVisible(true);  
       chatbot.acc.setText(lbl1.getText());
       chatbot.name4.setText(name1.getText());
    }//GEN-LAST:event_botMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);                                        
                customerauth ob=new customerauth();
            ob.setVisible(true);  
            if(date.getText().isEmpty()||time.getText().isEmpty()||lbl1.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "OOpps");
            }else{
               custlogout1(); 
            }
            
            
    }//GEN-LAST:event_logoutActionPerformed

    private void detailtransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailtransMouseClicked
        // TODO add your handling code here:
        setVisible(false);                                        
                detail_trans ob=new detail_trans();
            ob.setVisible(true);  
            
detail_trans.accountno.setText(lbl1.getText());
detail_trans.name3.setText(name1.getText());

         String acb=lbl1.getText();
       try{
           String sql="select  Date,Time,Credit,Debit,Balance,creditor as 'Particulars' from Transactions where Acc_no='"+acb+"'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           detail_trans.jtbl.setModel(DbUtils.resultSetToTableModel(rs));
           
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);              //customer list
       }finally{
           try{
               rs.close();
               pst.close();
               
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
       }
     
    }//GEN-LAST:event_detailtransMouseClicked

    private void miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseClicked
        // TODO add your handling code here:
         setVisible(false);                                        
                min ob=new min();
            ob.setVisible(true);
min.x.setText(lbl1.getText());
min.name2.setText(name1.getText());

            
            //fetch balance
            String sql="select Balances from Balances2 where Acc_No=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1,lbl1.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Balances");
                min.bal2.setText(add1);
                rs.close();
                pst.close();
 }
  else
  {
 JOptionPane.showMessageDialog(null, "Account Number is not correct");
  }
 }
  catch(Exception e){
  JOptionPane.showMessageDialog(null, e);
   } finally{
            try{
                rs.close();
                pst.close();
   }catch(Exception e){
  }
  }
        //mini statement
       String ac=lbl1.getText();
       try{
           String sql1="select  Date,Time,Credit,Debit,creditor as 'Particulars' from Transactions where Acc_no='"+ac+"' ORDER BY ROWID DESC LIMIT 5";
           pst=conn.prepareStatement(sql1);
           rs=pst.executeQuery();
           min.xtable.setModel(DbUtils.resultSetToTableModel(rs));
   }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);            
       }finally{
           try{
               rs.close();
               pst.close();
               
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
       }
    }//GEN-LAST:event_miniMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
/*   setVisible(false);                                        
                feedback ob=new feedback();
            ob.setVisible(true);
           feedback.name6.setText(name1.getText()); 
           feedback.yup.setText(lbl1.getText());
            
             String sql="select Email from Balances2 where Acc_No=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1,lbl1.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Email");
                feedback.id.setText(add1);
                rs.close();
                pst.close();
 }
  else
  {
 JOptionPane.showMessageDialog(null, "Account Number is not correct");
  }
 }
  catch(Exception e){
  JOptionPane.showMessageDialog(null, e);
   } finally{
            try{
                rs.close();
                pst.close();
   }catch(Exception e){
  }
  }*/
try {
        Desktop.getDesktop().browse(new URL("https://docs.google.com/forms/d/e/1FAIpQLSfKf9xmfvZL1JnJ49DNSuln0GwduyqYUrsp4w-R8OUHLTF2xA/viewform?usp=pp_url&entry.1591633300&entry.1696159737&entry.485428648").toURI());
        } 
       catch (IOException | URISyntaxException e) {
       JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer_portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer_portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer_portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer_portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer_portal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bot;
    private javax.swing.JTextField date;
    private javax.swing.JLabel deposit;
    private javax.swing.JLabel detailtrans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lbl1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel mini;
    public static javax.swing.JLabel name1;
    private javax.swing.JTextField time;
    private javax.swing.JLabel transfer;
    private javax.swing.JLabel withdraw;
    // End of variables declaration//GEN-END:variables
}
